name: scales
description: "Mi Body composition scales integration with Medsenger" 
publish_to: 'none'

version: 1.0.1+7

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_platform_widgets: ^7.0.1
  device_info_plus: ^11.0.0
  permission_handler: ^11.3.1
  xiaomi_scale: ^2.2.1
  shared_preferences: ^2.3.2
  app_links: ^6.3.2
  http: ^1.2.2
  intl: ^0.19.0
  flutter_blue_plus: ^1.33.4
  flutter_reactive_ble: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
